tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-high": "#e6e8ea",
                "surface-tint": "#5c5d6e",
                "on-tertiary-container": "#5b6a73",
                "primary-fixed": "#e1e1f5",
                "on-primary-fixed-variant": "#444655",
                "outline-variant": "#c7c5cc",
                "primary": "#5c5d6e",
                "on-primary": "#ffffff",
                "secondary-fixed": "#d4e6e5",
                "secondary-container": "#d4e6e5",
                "primary-container": "#e6e6fa",
                "surface-bright": "#f7f9fb",
                "tertiary": "#526069",
                "tertiary-container": "#dbeaf5",
                "outline": "#77767d",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "on-secondary-container": "#576867",
                "secondary": "#516161",
                "on-secondary-fixed": "#0e1e1e",
                "on-surface-variant": "#46464c",
                "surface-variant": "#e0e3e5",
                "on-background": "#191c1e",
                "tertiary-fixed-dim": "#bac9d3",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#eff1f3",
                "on-secondary-fixed-variant": "#3a4a49",
                "surface": "#f7f9fb",
                "inverse-primary": "#c5c5d8",
                "primary-fixed-dim": "#c5c5d8",
                "secondary-fixed-dim": "#b8cac9",
                "on-tertiary-fixed": "#0f1d25",
                "on-tertiary-fixed-variant": "#3b4951",
                "on-tertiary": "#ffffff",
                "surface-container-highest": "#e0e3e5",
                "error": "#ba1a1a",
                "background": "#f7f9fb",
                "surface-container": "#eceef0",
                "surface-container-low": "#f2f4f6",
                "on-surface": "#191c1e",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "inverse-surface": "#2d3133",
                "tertiary-fixed": "#d6e5ef",
                "surface-dim": "#d8dadc",
                "on-primary-container": "#656677",
                "on-primary-fixed": "#191b29"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "base": "8px",
                "stack-lg": "48px",
                "gutter": "24px",
                "container-padding-desktop": "40px",
                "stack-sm": "12px",
                "container-padding-mobile": "20px",
                "stack-md": "24px",
                "margin-mobile": "16px",
                "margin-desktop": "48px"
            },
            "fontFamily": {
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "display-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "body-md": ["Inter"],
                "body-lg": ["Inter"],
                "label-caps": ["JetBrains Mono", "Inter"],
                "label-sm": ["Inter"],
                "label-md": ["Inter"],
                "data-tabular": ["JetBrains Mono", "Inter"]
            },
            "fontSize": {
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
                "data-tabular": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        }
    }
};
